In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
rng = np.random.RandomState(1)

In [2]:
# Train dataset
dataset_size = 128
X_train = rng.rand(dataset_size,2)
Y_train = [ [int(x1+x2<1),int(x1+x2>=1)] for (x1,x2) in X_train]
print (Y_train)

[[0, 1], [1, 0], [1, 0], [1, 0], [1, 0], [0, 1], [0, 1], [1, 0], [1, 0], [1, 0], [0, 1], [0, 1], [0, 1], [1, 0], [0, 1], [1, 0], [0, 1], [0, 1], [0, 1], [1, 0], [0, 1], [0, 1], [1, 0], [0, 1], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [0, 1], [1, 0], [0, 1], [1, 0], [0, 1], [0, 1], [0, 1], [1, 0], [1, 0], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [1, 0], [0, 1], [1, 0], [1, 0], [0, 1], [0, 1], [1, 0], [0, 1], [1, 0], [0, 1], [1, 0], [0, 1], [1, 0], [1, 0], [1, 0], [0, 1], [0, 1], [1, 0], [0, 1], [1, 0], [0, 1], [0, 1], [0, 1], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [0, 1], [1, 0], [1, 0], [1, 0], [0, 1], [1, 0], [0, 1], [1, 0], [1, 0], [0, 1], [0, 1], [1, 0], [0, 1], [1, 0], [1, 0], [1, 0], [1, 0], [0, 1], [1, 0], [0, 1], [1, 0], [0, 1], [0, 1], [1, 0], [0, 1], [0, 1], [0, 1], [1, 0], [0, 1], [0, 1], [0, 1], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [1, 0], [0, 1], [0, 1], [1, 0], [0, 1], [1, 0], [0, 1],

In [7]:
Y_train[0:8]

[[0, 1], [1, 0], [1, 0], [1, 0], [1, 0], [0, 1], [0, 1], [1, 0]]

In [3]:
# Test dataset
X_test = rng.rand(20,2)
Y_test = [ [int(x1+x2<1),int(x1+x2>=1)] for (x1,x2) in X_test]

In [12]:
batch_size = 8
learning_rate = 0.003
training_epochs = 9

In [13]:
x = tf.placeholder(shape=[None,2],dtype=tf.float32)
y = tf.placeholder(shape=[None,2],dtype=tf.float32)

# Set model weights
w1 = tf.Variable(tf.random_normal([2, 3],stddev=1,seed=1))
w2 = tf.Variable(tf.random_normal([3, 2],stddev=1,seed=1))
b1 = tf.Variable(tf.random_normal([3],stddev=1,seed=1))
b2 = tf.Variable(tf.random_normal([2],stddev=1,seed=1))

# Construct model
h1 = tf.matmul(x,w1) + b1
pred = tf.nn.softmax(tf.matmul(h1,w2)+b2)

# Minimize error using cross entropy
cross_entropy = tf.reduce_mean(-tf.reduce_sum(y*tf.log(pred)))

# Gradient Descent
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cross_entropy)

# Initializing the variables
init = tf.global_variables_initializer()

In [21]:
with tf.Session() as sess:
    sess.run(init)
    print (sess.run(w1))
    print (sess.run(w2))
    step = 17000
    for i in range(step):        
        start = (i*batch_size) % dataset_size
        end = min(start + batch_size,dataset_size)
        sess.run(optimizer, feed_dict={x: X_train[start:end], y: Y_train[start:end]})
        if i % 1000 == 0:
            total_cross_entropy = sess.run(cross_entropy, feed_dict={x: X_train, y: Y_train})
            print ("Step:", '%05d' % i, "cost=", "{:.9f}".format(total_cross_entropy))
    print ("Optimization Finished!")
    
    # Test model
    Y_pred = tf.argmax(pred, 1)
    Y_real = tf.argmax(y, 1)
    correct_prediction = tf.equal(tf.argmax(pred, 1), tf.argmax(y, 1))
    # Calculate accuracy for 3000 examples
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
    print ("Accuracy:", accuracy.eval({x:X_test, y:Y_test}))
    #Y_pred = pred.eval({x:X_test})
    print (sess.run(Y_pred, feed_dict={x: X_test}))
    print (sess.run(Y_real, feed_dict={y: Y_test}))

[[-0.8113182   1.4845988   0.06532937]
 [-2.4427042   0.0992484   0.5912243 ]]
[[-0.8113182   1.4845988 ]
 [ 0.06532937 -2.4427042 ]
 [ 0.0992484   0.5912243 ]]
Step: 00000 cost= 691.742431641
Step: 01000 cost= 22.195419312
Step: 02000 cost= 14.612421989
Step: 03000 cost= 11.782528877
Step: 04000 cost= 9.987293243
Step: 05000 cost= 8.894448280
Step: 06000 cost= 7.953775883
Step: 07000 cost= 7.344328403
Step: 08000 cost= 6.729755402
Step: 09000 cost= 6.336392403
Step: 10000 cost= 5.888735294
Step: 11000 cost= 5.614371300
Step: 12000 cost= 5.266350269
Step: 13000 cost= 5.065927505
Step: 14000 cost= 4.783364296
Step: 15000 cost= 4.632598400
Step: 16000 cost= 4.395970345
Optimization Finished!
Accuracy: 1.0
[1 0 1 1 1 1 0 0 1 1 0 1 1 0 1 1 1 1 1 0]
[1 0 1 1 1 1 0 0 1 1 0 1 1 0 1 1 1 1 1 0]


In [ ]:
a = rng.rand(10,1)
a = [int(i>0.5) for i in a ]
a = np.array(a)
print(a)