In [2]:
import tensorflow as tf

# Import MINST data
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [3]:
# Parameters
learning_rate = 0.01
training_epochs = 25
batch_size = 100
display_step = 1

# tf Graph Input
x = tf.placeholder(tf.float32, [None, 784]) # mnist data image of shape 28*28=784
y = tf.placeholder(tf.float32, [None, 10]) # 0-9 digits recognition => 10 classes

# Set model weights
W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))

# Construct model
pred = tf.nn.softmax(tf.matmul(x, W) + b) # Softmax

# Minimize error using cross entropy
cost = tf.reduce_mean(-tf.reduce_sum(y*tf.log(pred), reduction_indices=1))
# Gradient Descent
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

# Initializing the variables
init = tf.global_variables_initializer()

In [6]:
# Launch the graph
with tf.Session() as sess:
    sess.run(init)

    # Fit all training data
    for epoch in range(training_epochs):
        avg_cost = 0.
        total_batch = int(mnist.train.num_examples/batch_size)
        for i in range(total_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            sess.run(optimizer, feed_dict= {x: batch_xs, y:batch_ys })
            c = sess.run(cost, feed_dict = {x: batch_xs, y:batch_ys })
            # Compute average loss
            avg_cost += c / total_batch
        #Display logs per epoch step
        if (epoch+1) % display_step == 0:
            print ("Epoch:", '%04d' % (epoch+1), "cost=", "{:.9f}".format(avg_cost))

    print ("Optimization Finished!")
    
    # Test model
    correct_prediction = tf.equal(tf.argmax(pred, 1), tf.argmax(y, 1))
    # Calculate accuracy for 3000 examples
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
    print ("Accuracy:", accuracy.eval({x: mnist.test.images[:3000], y: mnist.test.labels[:3000]}))
    print(y)

Epoch: 0001 cost= 1.176718193
Epoch: 0002 cost= 0.662551403
Epoch: 0003 cost= 0.550614973
Epoch: 0004 cost= 0.496815456
Epoch: 0005 cost= 0.463574010
Epoch: 0006 cost= 0.441131710
Epoch: 0007 cost= 0.423831248
Epoch: 0008 cost= 0.410549431
Epoch: 0009 cost= 0.399946617
Epoch: 0010 cost= 0.390948663
Epoch: 0011 cost= 0.383256462
Epoch: 0012 cost= 0.377072526
Epoch: 0013 cost= 0.370748563
Epoch: 0014 cost= 0.365896375
Epoch: 0015 cost= 0.361373289
Epoch: 0016 cost= 0.357436496
Epoch: 0017 cost= 0.353614433
Epoch: 0018 cost= 0.350006766
Epoch: 0019 cost= 0.346879798
Epoch: 0020 cost= 0.344099103
Epoch: 0021 cost= 0.341828673
Epoch: 0022 cost= 0.338668912
Epoch: 0023 cost= 0.336698773
Epoch: 0024 cost= 0.334650954
Epoch: 0025 cost= 0.332589610
Optimization Finished!
Accuracy: 0.889
Tensor("Placeholder_1:0", shape=(?, 10), dtype=float32)


In [7]:
print (tf.argmax(y, 1))

Tensor("ArgMax_4:0", shape=(?,), dtype=int64)


In [ ]:
mnist.train.num_examples/batch_size

In [10]:
print (mnist.train.labels)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
